// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package usingflume.ch03;

public final class UsingFlumeEvent {
  private UsingFlumeEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .Header header = 1;
    java.util.List<usingflume.ch03.UsingFlumeEvent.Header> 
        getHeaderList();
    usingflume.ch03.UsingFlumeEvent.Header getHeader(int index);
    int getHeaderCount();
    java.util.List<? extends usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder> 
        getHeaderOrBuilderList();
    usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder getHeaderOrBuilder(
        int index);
    
    // required bytes body = 2;
    boolean hasBody();
    com.google.protobuf.ByteString getBody();
  }
  public static final class Event extends
      com.google.protobuf.GeneratedMessage
      implements EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(Builder builder) {
      super(builder);
    }
    private Event(boolean noInit) {}
    
    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }
    
    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return usingflume.ch03.UsingFlumeEvent.internal_static_Event_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return usingflume.ch03.UsingFlumeEvent.internal_static_Event_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated .Header header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private java.util.List<usingflume.ch03.UsingFlumeEvent.Header> header_;
    public java.util.List<usingflume.ch03.UsingFlumeEvent.Header> getHeaderList() {
      return header_;
    }
    public java.util.List<? extends usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder> 
        getHeaderOrBuilderList() {
      return header_;
    }
    public int getHeaderCount() {
      return header_.size();
    }
    public usingflume.ch03.UsingFlumeEvent.Header getHeader(int index) {
      return header_.get(index);
    }
    public usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder getHeaderOrBuilder(
        int index) {
      return header_.get(index);
    }
    
    // required bytes body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    public boolean hasBody() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    
    private void initFields() {
      header_ = java.util.Collections.emptyList();
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getHeaderCount(); i++) {
        if (!getHeader(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < header_.size(); i++) {
        output.writeMessage(1, header_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, body_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < header_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static usingflume.ch03.UsingFlumeEvent.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static usingflume.ch03.UsingFlumeEvent.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static usingflume.ch03.UsingFlumeEvent.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(usingflume.ch03.UsingFlumeEvent.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements usingflume.ch03.UsingFlumeEvent.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return usingflume.ch03.UsingFlumeEvent.internal_static_Event_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return usingflume.ch03.UsingFlumeEvent.internal_static_Event_fieldAccessorTable;
      }
      
      // Construct using usingflume.ch03.UsingFlumeEvent.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          headerBuilder_.clear();
        }
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return usingflume.ch03.UsingFlumeEvent.Event.getDescriptor();
      }
      
      public usingflume.ch03.UsingFlumeEvent.Event getDefaultInstanceForType() {
        return usingflume.ch03.UsingFlumeEvent.Event.getDefaultInstance();
      }
      
      public usingflume.ch03.UsingFlumeEvent.Event build() {
        usingflume.ch03.UsingFlumeEvent.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private usingflume.ch03.UsingFlumeEvent.Event buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        usingflume.ch03.UsingFlumeEvent.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public usingflume.ch03.UsingFlumeEvent.Event buildPartial() {
        usingflume.ch03.UsingFlumeEvent.Event result = new usingflume.ch03.UsingFlumeEvent.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            header_ = java.util.Collections.unmodifiableList(header_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof usingflume.ch03.UsingFlumeEvent.Event) {
          return mergeFrom((usingflume.ch03.UsingFlumeEvent.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(usingflume.ch03.UsingFlumeEvent.Event other) {
        if (other == usingflume.ch03.UsingFlumeEvent.Event.getDefaultInstance()) return this;
        if (headerBuilder_ == null) {
          if (!other.header_.isEmpty()) {
            if (header_.isEmpty()) {
              header_ = other.header_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHeaderIsMutable();
              header_.addAll(other.header_);
            }
            onChanged();
          }
        } else {
          if (!other.header_.isEmpty()) {
            if (headerBuilder_.isEmpty()) {
              headerBuilder_.dispose();
              headerBuilder_ = null;
              header_ = other.header_;
              bitField0_ = (bitField0_ & ~0x00000001);
              headerBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHeaderFieldBuilder() : null;
            } else {
              headerBuilder_.addAllMessages(other.header_);
            }
          }
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasBody()) {
          
          return false;
        }
        for (int i = 0; i < getHeaderCount(); i++) {
          if (!getHeader(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              usingflume.ch03.UsingFlumeEvent.Header.Builder subBuilder = usingflume.ch03.UsingFlumeEvent.Header.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addHeader(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .Header header = 1;
      private java.util.List<usingflume.ch03.UsingFlumeEvent.Header> header_ =
        java.util.Collections.emptyList();
      private void ensureHeaderIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          header_ = new java.util.ArrayList<usingflume.ch03.UsingFlumeEvent.Header>(header_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          usingflume.ch03.UsingFlumeEvent.Header, usingflume.ch03.UsingFlumeEvent.Header.Builder, usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder> headerBuilder_;
      
      public java.util.List<usingflume.ch03.UsingFlumeEvent.Header> getHeaderList() {
        if (headerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(header_);
        } else {
          return headerBuilder_.getMessageList();
        }
      }
      public int getHeaderCount() {
        if (headerBuilder_ == null) {
          return header_.size();
        } else {
          return headerBuilder_.getCount();
        }
      }
      public usingflume.ch03.UsingFlumeEvent.Header getHeader(int index) {
        if (headerBuilder_ == null) {
          return header_.get(index);
        } else {
          return headerBuilder_.getMessage(index);
        }
      }
      public Builder setHeader(
          int index, usingflume.ch03.UsingFlumeEvent.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeaderIsMutable();
          header_.set(index, value);
          onChanged();
        } else {
          headerBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setHeader(
          int index, usingflume.ch03.UsingFlumeEvent.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.set(index, builderForValue.build());
          onChanged();
        } else {
          headerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addHeader(usingflume.ch03.UsingFlumeEvent.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeaderIsMutable();
          header_.add(value);
          onChanged();
        } else {
          headerBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addHeader(
          int index, usingflume.ch03.UsingFlumeEvent.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeaderIsMutable();
          header_.add(index, value);
          onChanged();
        } else {
          headerBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addHeader(
          usingflume.ch03.UsingFlumeEvent.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.add(builderForValue.build());
          onChanged();
        } else {
          headerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addHeader(
          int index, usingflume.ch03.UsingFlumeEvent.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.add(index, builderForValue.build());
          onChanged();
        } else {
          headerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllHeader(
          java.lang.Iterable<? extends usingflume.ch03.UsingFlumeEvent.Header> values) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          super.addAll(values, header_);
          onChanged();
        } else {
          headerBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        return this;
      }
      public Builder removeHeader(int index) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.remove(index);
          onChanged();
        } else {
          headerBuilder_.remove(index);
        }
        return this;
      }
      public usingflume.ch03.UsingFlumeEvent.Header.Builder getHeaderBuilder(
          int index) {
        return getHeaderFieldBuilder().getBuilder(index);
      }
      public usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder getHeaderOrBuilder(
          int index) {
        if (headerBuilder_ == null) {
          return header_.get(index);  } else {
          return headerBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder> 
           getHeaderOrBuilderList() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(header_);
        }
      }
      public usingflume.ch03.UsingFlumeEvent.Header.Builder addHeaderBuilder() {
        return getHeaderFieldBuilder().addBuilder(
            usingflume.ch03.UsingFlumeEvent.Header.getDefaultInstance());
      }
      public usingflume.ch03.UsingFlumeEvent.Header.Builder addHeaderBuilder(
          int index) {
        return getHeaderFieldBuilder().addBuilder(
            index, usingflume.ch03.UsingFlumeEvent.Header.getDefaultInstance());
      }
      public java.util.List<usingflume.ch03.UsingFlumeEvent.Header.Builder> 
           getHeaderBuilderList() {
        return getHeaderFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          usingflume.ch03.UsingFlumeEvent.Header, usingflume.ch03.UsingFlumeEvent.Header.Builder, usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              usingflume.ch03.UsingFlumeEvent.Header, usingflume.ch03.UsingFlumeEvent.Header.Builder, usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder>(
                  header_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      
      // required bytes body = 2;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Event)
    }
    
    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Event)
  }
  
  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // required string val = 2;
    boolean hasVal();
    String getVal();
  }
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(Builder builder) {
      super(builder);
    }
    private Header(boolean noInit) {}
    
    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }
    
    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return usingflume.ch03.UsingFlumeEvent.internal_static_Header_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return usingflume.ch03.UsingFlumeEvent.internal_static_Header_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string val = 2;
    public static final int VAL_FIELD_NUMBER = 2;
    private java.lang.Object val_;
    public boolean hasVal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getVal() {
      java.lang.Object ref = val_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          val_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValBytes() {
      java.lang.Object ref = val_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        val_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      key_ = "";
      val_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static usingflume.ch03.UsingFlumeEvent.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static usingflume.ch03.UsingFlumeEvent.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static usingflume.ch03.UsingFlumeEvent.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static usingflume.ch03.UsingFlumeEvent.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(usingflume.ch03.UsingFlumeEvent.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements usingflume.ch03.UsingFlumeEvent.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return usingflume.ch03.UsingFlumeEvent.internal_static_Header_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return usingflume.ch03.UsingFlumeEvent.internal_static_Header_fieldAccessorTable;
      }
      
      // Construct using usingflume.ch03.UsingFlumeEvent.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return usingflume.ch03.UsingFlumeEvent.Header.getDescriptor();
      }
      
      public usingflume.ch03.UsingFlumeEvent.Header getDefaultInstanceForType() {
        return usingflume.ch03.UsingFlumeEvent.Header.getDefaultInstance();
      }
      
      public usingflume.ch03.UsingFlumeEvent.Header build() {
        usingflume.ch03.UsingFlumeEvent.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private usingflume.ch03.UsingFlumeEvent.Header buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        usingflume.ch03.UsingFlumeEvent.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public usingflume.ch03.UsingFlumeEvent.Header buildPartial() {
        usingflume.ch03.UsingFlumeEvent.Header result = new usingflume.ch03.UsingFlumeEvent.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.val_ = val_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof usingflume.ch03.UsingFlumeEvent.Header) {
          return mergeFrom((usingflume.ch03.UsingFlumeEvent.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(usingflume.ch03.UsingFlumeEvent.Header other) {
        if (other == usingflume.ch03.UsingFlumeEvent.Header.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasVal()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              val_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // required string val = 2;
      private java.lang.Object val_ = "";
      public boolean hasVal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getVal() {
        java.lang.Object ref = val_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          val_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVal(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        val_ = value;
        onChanged();
        return this;
      }
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        val_ = getDefaultInstance().getVal();
        onChanged();
        return this;
      }
      void setVal(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        val_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Header)
    }
    
    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Header)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Event_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Header_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\".\n\005Event\022\027\n\006header\030\001 \003(\0132\007" +
      ".Header\022\014\n\004body\030\002 \002(\014\"\"\n\006Header\022\013\n\003key\030\001" +
      " \002(\t\022\013\n\003val\030\002 \002(\tB\"\n\017usingflume.ch03B\017Us" +
      "ingFlumeEvent"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Event_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Event_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Event_descriptor,
              new java.lang.String[] { "Header", "Body", },
              usingflume.ch03.UsingFlumeEvent.Event.class,
              usingflume.ch03.UsingFlumeEvent.Event.Builder.class);
          internal_static_Header_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Header_descriptor,
              new java.lang.String[] { "Key", "Val", },
              usingflume.ch03.UsingFlumeEvent.Header.class,
              usingflume.ch03.UsingFlumeEvent.Header.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
